config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "(:locale)", locale: /en|vi/ do

    resources :chairs
    resource :cart, only: [:show]
    resources :order_items, only: [:create, :update, :destroy]

    get 'admin/dashboard'

    get 'chart', to: 'admin#show_chart'

    root "static_pages#home"
     #contact
    get 'contact', to: 'static_pages#contact'
    get 'about', to: 'static_pages#about'
    #resources users
    resources :users,  only: [:index, :edit, :update]

    resources :billings, only: [:new, :create, :index, :show, :delete]
    namespace :admin do
      resources :users
      resources :chairs
      resources :categories
      resources :billings, only: [:index, :show]
      resources :brands
    end
    
    #rating
    post 'rating', to: 'chairs#rating'
    get 'rating', to: 'chairs#get_rating'
    #autocomplete search
    post 'search_chair', to: 'chairs#get_chair_by_key'
   
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = current_order
    @order_items = @order.order_items
  end
end

app/views/carts/_cart_row.html.erb
<!-- breadcrumb start-->

<!--================Cart Area =================-->
<tr>
  <td>
    <div class="media">
      <div class="d-flex">
        <%= image_tag chair.img, width: '127' %>
      </div>
      <div class="media-text">
        <p><%= chair.name %></p>
        <%= link_to "Delete", order_item, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </td>
  <td>
    <h5>$<%= chair.price %></h5>
  </td>
  <td>
    <div class="product_count">
      <span class="input-number-decrement" id = "minus"> <i class="ti-angle-down"></i></span>
      <input value="<%=order_item.quantity%>" class="input-number" min="1" type="text" name="order_item[quantity]" id="order_item_quanity">
      <input type="hidden" value="<%=order_item.id%>" id = "order_item_id">
      <span class="input-number-increment" id = "plus"> <i class="ti-angle-up"></i></span>
    </div>
  </td>
  <td>
    <h5>$<%= order_item.total_price.round %></h5>
  </td>
</tr>
<script>
  $(function(){
    $( ".input-number-decrement" ).click(function() {
      var quantity = Number($('#order_item_quanity').val()) - 1;
      var order_item_id = $('#order_item_id').val();
      $.ajax({
        method: "put",
        url: "/order_items/"+order_item_id,
        data: {'quantity': quantity},
        success: function (res) {
        },
      });
    });
    $( ".input-number-increment" ).click(function() {
      var quantity = Number($('#order_item_quanity').val()) + 1;
      var order_item_id = $('#order_item_id').val();
      $.ajax({
        method: "put",
        url: "/order_items/"+order_item_id,
        data: {'quantity': quantity},
        success: function (res) {
        },
      });
    });
    $('#order_item_quanity').keypress(function(event) {
    if (event.keyCode == 13 || event.which == 13) {
        var quantity = Number($('#order_item_quanity').val());
        var order_item_id = $('#order_item_id').val();
        $.ajax({
          method: "put",
          url: "/order_items/"+order_item_id,
          data: {'quantity': quantity},
          success: function (res) {
          },
        });  
      }
    });
  })
</script>

app/views/carts/_shopping_cart.html.erb
<section class="breadcrumb breadcrumb_bg">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="breadcrumb_iner">
          <div class="breadcrumb_iner_item">
            <h2><%=t("cart.shopping_cart")%></h2>
            <p><%=t("home")%> <span>-</span><%=t("cart.shopping_cart")%></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    <%=t("cart.no_items")%> <%= link_to t("cart.go_back"), root_path %>
  </p>
<% else %>
  <section class="cart_area padding_top">
    <div class="container">
      <div class="cart_inner">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col"><%=t("cart.product")%></th>
                <th scope="col"><%=t("cart.price")%></th>
                <th scope="col"><%=t("cart.quantity")%></th>
                <th scope="col"><%=t("cart.total")%></th>
              </tr>
            </thead>
            <tbody>
              <% @order_items.each do |order_item| %>
                <%= render 'carts/cart_row', chair: order_item.chair, order_item: order_item, show_total: true %>
              <% end %>

              <% if false %>
                <tr class="bottom_button">
                  <td>
                    <a class="btn_1" href="#">Update Cart</a>
                  </td>
                  <td></td>
                  <td></td>
                  <td>
                    <div class="cupon_text float-right">
                      <a class="btn_1" href="#">Close Coupon</a>
                    </div>
                  </td>
                </tr>
              <% end %>
              <tr>
                <td></td>
                <td></td>
                <td>
                  <h5><%=t("cart.sub_total")%></h5>
                </td>
                <td>
                  <h5>$<%= @order.subtotal.round %></h5>
                </td>
              </tr>

              <% if false %>
                <tr class="shipping_area">
                  <td></td>
                  <td></td>
                  <td>
                    <h5>Shipping</h5>
                  </td>
                  <td>
                    <div class="shipping_box">
                      <ul class="list">
                        <li>
                          <a href="#">Flat Rate: $5.00</a>
                        </li>
                        <li>
                          <a href="#">Free Shipping</a>
                        </li>
                        <li>
                          <a href="#">Flat Rate: $10.00</a>
                        </li>
                        <li class="active">
                          <a href="#">Local Delivery: $2.00</a>
                        </li>
                      </ul>
                      <h6>
                        Calculate Shipping
                        <i class="fa fa-caret-down" aria-hidden="true"></i>
                      </h6>
                      <select class="shipping_select">
                        <option value="1">Bangladesh</option>
                        <option value="2">India</option>
                        <option value="4">Pakistan</option>
                      </select>
                      <select class="shipping_select section_bg">
                        <option value="1">Select a State</option>
                        <option value="2">Select a State</option>
                        <option value="4">Select a State</option>
                      </select>
                      <input type="text" placeholder="Postcode/Zipcode" />
                      <a class="btn_1" href="#">Update Details</a>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <div class="checkout_btn_inner float-right">
            <%= link_to t("cart.continute_shopping"), chairs_path, class: 'btn_1', method: :get %>
            <%= link_to t("cart.proceed_checkout"), new_billing_path, class: 'btn_1 checkout_btn_1', method: :get %>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/carts/show.html.erb
<%= stylesheet_link_tag "css/nice-select.css" %>
<%= javascript_include_tag "js/contact.js" %>
<%= javascript_include_tag "js/price_rangs.js" %>
<%= javascript_include_tag "js/stellar.js" %>

<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>