config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "(:locale)", locale: /en|vi/ do

    resources :chairs
    resource :cart, only: [:show]
    resources :order_items, only: [:create, :update, :destroy]

    get 'admin/dashboard'

    get 'chart', to: 'admin#show_chart'

    root "static_pages#home"
     #contact
    get 'contact', to: 'static_pages#contact'
    get 'about', to: 'static_pages#about'
    #resources users
    resources :users,  only: [:index, :edit, :update]

    resources :billings, only: [:new, :create, :index, :show, :delete]
    namespace :admin do
      resources :users
      resources :chairs
      resources :categories
      resources :billings, only: [:index, :show]
      resources :brands
    end
    
    #rating
    post 'rating', to: 'chairs#rating'
    get 'rating', to: 'chairs#get_rating'
    #autocomplete search
    post 'search_chair', to: 'chairs#get_chair_by_key'
   
  end
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    has_many :chairs
    has_many :brands
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_filter :verify_is_admin
  before_action :find_category, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  layout 'admin'
  def index
    @search = Category.order(id: :desc).ransack params[:q]
    @categories = @search.result.page(params[:page]).per 9
  end
  
  def new
    @categories = Chair.new
  end
  
  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = "Successfully!!!"
      redirect_to admin_categories_path
    else
      flash[:danger] = "Can not create new category"
      redirect_to :back
    end  
  end
  
  def edit
  end
  
  def update
    # @user = find_user
    if @category.update_attributes category_params
      flash[:success] = "Info category updated"
      redirect_to admin_categories_path
    else
      flash[:danger] = "Can not update new category"
      redirect_to :back
    end
  end
  
  def destroy
    Chair.where(category_id: params[:id]).destroy_all
    @category.destroy
  end 
  private
  
  def verify_is_admin
    (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  end
  
  def category_params
    params.require(:category).permit(:name, :description)
  end
  
  def find_category
    @category = Category.find_by id: params[:id]
    return @category if @category
    flash[:warning] = "Can not find category"
    redirect_to admin_categories_path
  end
end

app/views/admin/categories/edit.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      Edit chair
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Category</li>
      <li class="active">Edit</li>
    </ol>
  </section>
  <br>
  <section class="container-fluid" style="background-color:white;margin: 0 10px 0px 10px;border-radius:5px;height:1000px">
    <div style="margin-top:20px" class="col-xs-9 col-xs-offset-1">
      <%= form_for(@category, as: :category,:html => {:class => 'row'}, url: admin_category_path(@category.id), method: :put) do |f| %>
        <% flash.each do |key, value| %>
          <div id="error_explanation" style="mt-5">
            <div class="alert alert-danger col-lg-6 col-lg-offset-3">
               <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
               <strong><%= value unless value.blank? %>!</strong>
            </div>
          </div>
        <% end %>
        <div class="col-md-12 form-group p_star">
          <label>Name</label>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "Name", value: @category.name%>
        </div>
        <div class="col-md-12 form-group p_star">
          <label>Description</label>
          <%= f.text_area :description, autofocus: true, autocomplete: "description", class: "form-control", placeholder: "Description", value: @category.description %>
        </div>
        <div class="col-md-2 col-md-offset-5 form-group">
          <%= f.submit "Update", class: "btn btn-success", data: { confirm: "Do you want to update?" }, style:'width:100px;margin-top:50px'  %>
        </div>
      <% end %>
    </div>
  </section>
  
</div>

app/views/admin/categories/index.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      Category List
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Category</li>
      <li class="active">List</li>
    </ol>
  </section>
  <br>
  <section class="container-fluid" style="background-color:white;margin: 0 10px 0px 10px;border-radius:5px; height:1000px">
    <div style="margin-top:20px">
      <div class="col-lg-8">
        <%= link_to "New", new_admin_category_path, :class=>'btn btn-primary', :style=>'width:100px'%>
      </div>
      <div class="col-xs-4"> 
        <div class="input-group">
          <%= search_form_for @search, class: "input-group-btn search-panel",   url: admin_categories_path do |f|%>
            <%= f.search_field :name_cont, class: "form-control", placeholder: "Seach by name", style: "float:left;width:300px" %>
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
            </span>
          <%end%>
        </div>
      </div>
      
    </div>
    <div style="margin-top:70px;" >
      <div id="response-success" style="mt-5">
        
      </div>
      <table class="table table-bordered">
        <thead class="thead-dark">
          <tr>
            <th scope="col" width="3%">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col" width="14%" ></th>
          </tr>
        </thead>
        <tbody>
            <%@categories.each do |category| %>
              <tr>
                <td><%= category.id %></td>
                <td><%= category.name %></td>
                <td><%= category.description %></td>
                <td><%= link_to "Edit", edit_admin_category_path(category.id), class: 'btn btn-warning', style: 'width:63px;margin-bottom:2px'%>
                    <button class = "btn btn-danger delete" id = "<%=category.id%>" >Delete</button>
                </td>
              </tr>
            <% end %>
        </tbody>
      </table>
      <div class="col-lg-4 col-lg-offset-4">
          <%= paginate @categories, theme: 'twitter-bootstrap-3' %>
      </div> 
    </div>
  </section>
</div>

<script>
  $(function(){
    $( ".delete" ).click(function() {
      var id = $(this).attr('id')
      var childTr = $(this).closest('tr')
      if(confirm("Are you sure?")){
        $.ajax({
          method: "delete",
          url: "/admin/categories/"+id,
          success: function (res) {
            childTr.hide();   //ẩn đi thẻ được gán
            $( "#response-success" ).append( "<div class='alert alert-danger col-lg-6 col-lg-offset-3'><a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong>Delete success!</strong></div>" );
            setTimeout(function(){ $('#response-success').hide(); }, 3000);
            childTr.hide();
          },
        });
      }

    });
  })
</script>

app/views/admin/categories/new.html.erb
<div class="content-wrapper">
  <section class="content-header">
    <h1>
      New category
    </h1>
    <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active">Category</li>
      <li class="active">New</li>
    </ol>
  </section>
  <br>
  <section class="container-fluid" style="background-color:white;margin: 0 10px 0px 10px;border-radius:5px;height:1000px">
    <div style="margin-top:20px" class="col-xs-9 col-xs-offset-1">
      <% flash.each do |key, value| %>
        <div id="error_explanation" style="mt-5">
          <div class="alert alert-danger col-lg-6 col-lg-offset-3">
             <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
             <strong><%= value unless value.blank? %>!</strong>
          </div>
        </div>
      <% end %>
      <%= form_for(Category.new, as: :category,:html => {:class => 'row'}, url: admin_categories_path, method: :post) do |f| %>
        <div class="col-md-12 form-group p_star">
          <label>Name</label>
          <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "form-control", placeholder: "Name"%>
        </div>
        <div class="col-md-12 form-group p_star">
          <label>Description</label>
          <%= f.text_area :description, autofocus: true, autocomplete: "description", class: "form-control", placeholder: "Description" %>
        </div>
        <div class="col-md-2 col-md-offset-5 form-group">
          <%= f.submit "Create", class: "btn btn-primary", data: { confirm: "Do you want to create?" }, style:'width:100px;margin-top:50px'  %>
        </div>
      <% end %>
    </div>
  </section>
  
</div>