config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  scope "(:locale)", locale: /en|vi/ do

    resources :chairs
    resource :cart, only: [:show]
    resources :order_items, only: [:create, :update, :destroy]

    get 'admin/dashboard'

    get 'chart', to: 'admin#show_chart'

    root "static_pages#home"
     #contact
    get 'contact', to: 'static_pages#contact'
    get 'about', to: 'static_pages#about'
    #resources users
    resources :users,  only: [:index, :edit, :update]

    resources :billings, only: [:new, :create, :index, :show, :delete]
    namespace :admin do
      resources :users
      resources :chairs
      resources :categories
      resources :billings, only: [:index, :show]
      resources :brands
    end
    
    #rating
    post 'rating', to: 'chairs#rating'
    get 'rating', to: 'chairs#get_rating'
    #autocomplete search
    post 'search_chair', to: 'chairs#get_chair_by_key'
   
  end
end

app/views/layouts/_cart_quantity.html.erb
<p class="cart_quantity"><%= current_order.total_quantity %></p>

app/views/layouts/_footer.html.erb
<footer class="footer_part">
    <div class="container">
        <div class="row justify-content-around">
            <div class="col-sm-6 col-lg-2">
                <div class="single_footer_part">
                    <h4>Top Products</h4>
                    <ul class="list-unstyled">
                        <li><a href="">Managed Website</a></li>
                        <li><a href="">Manage Reputation</a></li>
                        <li><a href="">Power Tools</a></li>
                        <li><a href="">Marketing Service</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-lg-2">
                <div class="single_footer_part">
                    <h4>Quick Links</h4>
                    <ul class="list-unstyled">
                        <li><a href="">Jobs</a></li>
                        <li><a href="">Brand Assets</a></li>
                        <li><a href="">Investor Relations</a></li>
                        <li><a href="">Terms of Service</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-lg-2">
                <div class="single_footer_part">
                    <h4>Features</h4>
                    <ul class="list-unstyled">
                        <li><a href="">Jobs</a></li>
                        <li><a href="">Brand Assets</a></li>
                        <li><a href="">Investor Relations</a></li>
                        <li><a href="">Terms of Service</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-lg-2">
                <div class="single_footer_part">
                    <h4>Resources</h4>
                    <ul class="list-unstyled">
                        <li><a href="">Guides</a></li>
                        <li><a href="">Research</a></li>
                        <li><a href="">Experts</a></li>
                        <li><a href="">Agencies</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6 col-lg-4">
                <div class="single_footer_part">
                    <h4>Newsletter</h4>
                    <p>Heaven fruitful doesn't over lesser in days. Appear creeping
                    </p>
                    <div id="mc_embed_signup">
                        <form target="_blank"
                            action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
                            method="get" class="subscribe_form relative mail_part">
                            <input type="email" name="email" id="newsletter-form-email" placeholder="Email Address"
                                class="placeholder hide-on-focus" onfocus="this.placeholder = ''"
                                onblur="this.placeholder = ' Email Address '">
                            <button type="submit" name="submit" id="newsletter-submit"
                                class="email_icon newsletter-submit button-contactForm">subscribe</button>
                            <div class="mt-10 info"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <div class="copyright_part">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="copyright_text">
                        <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->Copyright &copy;2019 All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></P>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="footer_icon social_icon">
                        <ul class="list-unstyled">
                            <li><a href="#" class="single_social_icon"><i class="fab fa-facebook-f"></i></a></li>
                            <li><a href="#" class="single_social_icon"><i class="fab fa-twitter"></i></a></li>
                            <li><a href="#" class="single_social_icon"><i class="fas fa-globe"></i></a></li>
                            <li><a href="#" class="single_social_icon"><i class="fab fa-behance"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Load Facebook SDK for JavaScript -->
      <div id="fb-root"></div>
      <script>
        window.fbAsyncInit = function() {
          FB.init({
            xfbml            : true,
            version          : 'v5.0'
          });
        };

        (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js';
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));</script>

      <!-- Your customer chat code -->
      <div class="fb-customerchat"
        attribution=setup_tool
        page_id="104322267706873"
  logged_in_greeting="Chúng tôi có thể giúp gì cho bạn?"
  logged_out_greeting="Chúng tôi có thể giúp gì cho bạn?">
      </div>

app/views/layouts/_header.html.erb
<!--::header part start::-->
<header class="main_menu home_menu">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-12">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <%= link_to image_tag("img/logo.png", height: '48'), root_path, class: "navbar-brand" %>
                    <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="menu_icon"><i class="fas fa-bars"></i></span>
                    </button>

                    <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <%= link_to t("layouts._header.home"), root_path, class: "nav-link" %>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1"
                                    role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <%=t("layouts._header.shop")%>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                    <%= link_to t("layouts._header.shop_category"), chairs_path, class: "dropdown-item", method: :get %>
                                </div>
                            </li>
                            <li class="nav-item">
                                <%= link_to t("layouts._header.contact"), "/contact", class: "nav-link" %>
                            </li>
                            <li class="nav-item">
                                <%= link_to t("layouts._header.About"), "/about", class: "nav-link" %>
                            </li>
                        </ul>
                    </div>
                    <div class="hearer_icon d-flex">
                    <%= link_to image_tag("img/en.png", width: '30', height:'20'), '/en', style: "margin-right:10px" %>
                    <%= link_to image_tag("img/vi.png", width: '30'), '/vi', height: '20' %>                        
                    <div class="dropdown cart">
                        <%= link_to cart_path, class: 'dropdown-toggle' do %>
                            <i class="fas fa-cart-plus"></i>
                            <%= render "layouts/cart_quantity" %>
                        <% end %>
                            </a>
                            <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <div class="single_product">

                                </div>
                            </div> -->

                        </div>
                        <div class="dropdown">
                            <a class="dropdown-toggle" id="navbarDropdown_account" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-user"></i>
                            </a>
                            <% if user_signed_in? %>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown_account">
                                    <% if current_user.admin? %>
                                        <%= link_to t("layouts._header.admin_dashboard"), admin_dashboard_path, class: "dropdown-item" %>
                                    <% end %>
                                    <%= link_to t("layouts._header.my_account"), users_path, class: "dropdown-item" %>
                                    <%= link_to t("layouts._header.log_out"), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                                </div>
                            <% else %>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown_account">
                                    <%= link_to t("layouts._header.sign_in"), new_user_session_path, class: "dropdown-item" %>
                                    <%= link_to t("layouts._header.sign_up"), new_user_registration_path, class: "dropdown-item" %>
                                </div>
                            <% end %>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <div class="search_input" id="search_input_box">
        <div class="container ">
            <form class="d-flex justify-content-between search-inner">
                <input type="text" class="form-control" id="search_input" placeholder="Search Here">
                <button type="submit" class="btn"></button>
                <span class="ti-close" id="close_search" title="Close Search"></span>
            </form>
        </div>
    </div>
</header>
<!-- Header part end-->

app/views/layouts/_javascript.html.erb
<%= javascript_include_tag "js/jquery-1.12.1.min.js" %>
<%= javascript_include_tag "js/popper.min.js" %>
<%= javascript_include_tag "js/bootstrap.min.js" %>
<%= javascript_include_tag "js/jquery.magnific-popup.js" %>
<%= javascript_include_tag "js/swiper.min.js" %>
<%= javascript_include_tag "js/masonry.pkgd.js" %>
<%= javascript_include_tag "js/owl.carousel.min.js" %>
<%= javascript_include_tag "js/jquery.nice-select.min.js" %>
<%= javascript_include_tag "js/slick.min.js" %>
<%= javascript_include_tag "js/jquery.counterup.min.js" %>
<%= javascript_include_tag "js/waypoints.min.js" %>
<%= javascript_include_tag "js/jquery.ajaxchimp.min.js" %>
<%= javascript_include_tag "js/jquery.form.js" %>
<%= javascript_include_tag "js/jquery.validate.min.js" %>
<%= javascript_include_tag "js/mail-script.js" %>
<%= javascript_include_tag "js/custom.js" %>
<%= javascript_include_tag "js/che.js" %>
<%= javascript_include_tag "js/jquery-ui.min.js" %>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_stylesheet.html.erb
<%= stylesheet_link_tag "css/bootstrap.min.css" %>
<%= stylesheet_link_tag "css/animate.css" %>
<%= stylesheet_link_tag "css/owl.carousel.min.css" %>
<%= stylesheet_link_tag "css/all.css" %>
<%= stylesheet_link_tag "css/flaticon.css" %>
<%= stylesheet_link_tag "css/themify-icons.css" %>
<%= stylesheet_link_tag "css/magnific-popup.css" %>
<%= stylesheet_link_tag "css/slick.css" %>
<%= stylesheet_link_tag "css/style.css" %>
<%= stylesheet_link_tag "css/price_rangs.css" %>
<%= stylesheet_link_tag "css/rating.css" %>
<%= stylesheet_link_tag "css/jquery-ui.css" %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield 'title' %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'admin', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://cdn.ckeditor.com/4.13.0/standard/ckeditor.js"></script>

  </head>

  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <%= render "admin/header" %>
      <%= render "admin/left_sidebar" %>
      
      <%= yield %>

      <%= render "admin/footer" %>
      <%= render "admin/right_sidebar" %>

      <div class="control-sidebar-bg"></div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield 'title' %></title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/stylesheet" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= render "layouts/javascript" %>
  </body>
</html>